development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: disCoveR_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: disCoveR_test
  host: localhost
  pool: 5

